web/router.ex
defmodule Presenter.Router do
  use Presenter.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :secure do
    plug :accepts, ["html"]
    plug BasicAuth, use_config: {:presenter, :pass}
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin_layout do
    plug :put_layout, {Presenter.LayoutView, :admin}
  end

  pipeline :present_layout do
    plug :put_layout, {Presenter.LayoutView, :presenter}
  end

  scope "/", Presenter do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/present", Presenter do
    pipe_through :present_layout
    get "/", PageController, :present

    resources "/", PageController
  end

  scope "/prayers", Presenter do
    pipe_through [:secure, :admin_layout]

    get "/reboot", PrayerController, :reboot
    get "/confirm", PrayerController, :confirm
    get "/shutdown", PrayerController, :shutdown
    get "/confirmshutdown", PrayerController, :confirmshutdown

    get "/github", PrayerController, :github
    resources "/", PrayerController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Presenter do
  #   pipe_through :api
  # end
end

web/controllers/prayer_api_controller.ex
defmodule Presenter.PrayerApiController do
  use Presenter.Web, :controller

  alias Presenter.PrayerApi

  # GET http://localhost:4000/api/prayers/
  def index(conn, _params) do
    prayer_apis = File.read!(filejamaah) |> Poison.decode!()

    [fajr, dhuhr, asr, maghrib, isha] = prayer_apis
    IO.puts "+++++"
    IO.inspect fajr["id"]
    IO.inspect asr["method"]
    IO.puts "+++++"

    render conn, prayer_apis: prayer_apis
  end

  # GET http://localhost:4000/api/prayers/1
  def show(conn, params) do
    prayer_apis = File.read!(filejamaah) |> Poison.decode!()
    render conn, prayer_api: prayer_apis |> Enum.find(&(&1["id"] === String.to_integer(params["id"])))
  end

 
  defp filejamaah() do
    Path.join(:code.priv_dir(:timetable), "db/jamaah.json")
  end

  defp fileprayers() do
    Path.join(:code.priv_dir(:timetable), "db/jamaah2.json")
  end

end

web/templates/prayer_api/index.html.eex
    <style>
table {
    background-color: linen;
}

td, th {
    background: #fff;
    padding: 5px 10px;
    border: 1px solid #ccc;
} 
</style>


<table>
    <tr>
        <th>No</th>
        <th>Name</th>
        <th>Method</th>
        <th>Calc</th>
    </tr>
    <%= for prayer <- @prayers do %>
        <% if prayer["minute"] == "0" do
                minute = "00"
                else
                    minute = prayer["minute"]
            end
        %>
        <tr>
            <td><%= prayer["id"] %></td>
            <td><%= prayer["name"] %></td>
            <td><%= prayer["method"] %></td>
            <td><%= prayer["hour"] %> : <%= minute %></td>
        </tr>
<% end %>
</table>


    
    <%= link to: "/edit/new", class: "btn-floating btn-large waves-effect waves-light red" do %>
        <i class="material-icons">edit</i>
    <% end %>

web/templates/prayer_api/new.html.eex
<!--<ul>
    <li><%= @fajr["id"] %>. Prayer: <%= @fajr["prayer"] %>, Method: <%= @fajr["method"] %>, Number: <%= @fajr["number"] %></li>
    <li><%= @dhuhr["id"] %>. Prayer: <%= @dhuhr["prayer"] %>, Method: <%= @dhuhr["method"] %>, Number: <%= @dhuhr["number"] %></li>
    <li><%= @fajr["id"] %>. Prayer: <%= @fajr["prayer"] %>, Method: <%= @fajr["method"] %>, Number: <%= @fajr["number"] %></li>
    <li><%= @fajr["id"] %>. Prayer: <%= @fajr["prayer"] %>, Method: <%= @fajr["method"] %>, Number: <%= @fajr["number"] %></li>
    <li><%= @fajr["id"] %>. Prayer: <%= @fajr["prayer"] %>, Method: <%= @fajr["method"] %>, Number: <%= @fajr["number"] %></li>
</ul>-->

<style>
table {
    background-color: linen;
}

td, th {
    background: #fff;
    padding: 5px 10px;
    border: 1px solid #ccc;
} 
</style>


<%= form_for @conn, prayer_path(@conn, :create), [as: :prayers], fn f -> %>
    <table>
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Method</th>
            <th>Calc</th>
        </tr>
        <tr>
            <%# fajr %>
            <td>1</td>
            <td>Fajr</td>
            <td><%= select(f, :fajr_method, ["Fixed time": "fixed", "Before next": "beforenext", "After this": "afterthis"], value: @fajr["method"]) %></td>
            <td><%= select(f, :fajr_hour,[hour: 0..23], value: @fajr["hour"]) %> : <%= select(f, :fajr_minute,[minute: 0..59], value: @fajr["minute"]) %></td>
        </tr>
        <tr>
            <%# dhuhr %>
            <td>2</td>
            <td>Dhuhr</td>
            <td><%= select(f, :dhuhr_method, ["Fixed time": "fixed", "Before next": "beforenext", "After this": "afterthis"], value: @dhuhr["method"]) %></td>
            <td><%= select(f, :dhuhr_hour,[hour: 0..23], value: @dhuhr["hour"]) %> : <%= select(f, :dhuhr_minute,[minute: 0..59], value: @dhuhr["minute"]) %></td>
        </tr>
        <tr>
            <%# asr %>
            <td>3</td>
            <td>Asr</td>
            <td><%= select(f, :asr_method, ["Fixed time": "fixed", "Before next": "beforenext", "After this": "afterthis"], value: @asr["method"]) %></td>
            <td><%= select(f, :asr_hour,[hour: 0..23], value: @asr["hour"]) %> : <%= select(f, :asr_minute,[minute: 0..59], value: @asr["minute"]) %></td>
        </tr>
        <tr>
            <%# maghrib %>
            <td>4</td>
            <td>Maghrib</td>
            <td><%= select(f, :maghrib_method, ["Fixed time": "fixed", "Before next": "beforenext", "After this": "afterthis"], value: @maghrib["method"]) %></td>
            <td><%= select(f, :maghrib_hour,[hour: 0..23], value: @maghrib["hour"]) %> : <%= select(f, :maghrib_minute,[minute: 0..59], value: @maghrib["minute"]) %></td>
        </tr>
        <tr>
            <%# isha %>
            <td>5</td>
            <td>Isha</td>
            <td><%= select(f, :isha_method, ["Fixed time": "fixed", "Before next": "beforenext", "After this": "afterthis"], value: @isha["method"]) %></td>
            <td><%= select(f, :isha_hour,[hour: 0..23], value: @isha["hour"]) %> : <%= select(f, :isha_minute,[minute: 0..59], value: @isha["minute"]) %></td>
        </tr>


    </table>


  <%= submit "Submit" %>
<% end %>